// Bu dosya RAG kalite kapisi (quality gate) icin kullanilan degerlendirme setidir.
// 200 soru; seed.ts'teki 5 bilgi tabani dokumaniyla dogrulanmis (verified) beklenen
// sonuclari icerir: her soru gercekten calistirilip actual durum ile karsilastirilarak
// (bkz. scripts/_gen_200.ts) dogru kategoriye (grounded/partially_grounded,
// conflicting_sources, permission_denied, not_found) oturdugu teyit edilmistir.
//
// Kategoriler:
// - grounded/partially_grounded (70+0): hali/leke bakimi sorulari -> doc-bakim-001
// - conflicting_sources (40): garanti sorulari -> doc-garanti-conf-a / doc-garanti-conf-b catismasi
// - permission_denied (40): bayi ic komisyon sorulari -> doc-bayi-ic-001 (yetkisiz erisim)
// - not_found (50): bilgi tabaniyla alakasiz konular

import type { CustomerType, RagEvalExpectedStatus } from "../support-core/src/types.js"

export type RagEvalCase = {
	id: string
	question: string
	customerType: CustomerType
	expectedStatus: RagEvalExpectedStatus
	expectedDocumentId?: string
}

export const ragEvalTestSet: RagEvalCase[] = [
	{ id: "q1", question: "Halimdaki kahve lekesini nasil cikarabilirim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q2", question: "Halimdaki cay lekesini nasil cikarabilirim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q3", question: "Halimdaki sarap lekesini nasil cikarabilirim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q4", question: "Halimdaki yag lekesini nasil cikarabilirim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q5", question: "Halimdaki cikolata lekesini nasil cikarabilirim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q6", question: "Halimdaki kan lekesini nasil cikarabilirim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q7", question: "Halimdaki murekkep lekesini nasil cikarabilirim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q8", question: "Halimdaki boya lekesini nasil cikarabilirim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q9", question: "Halimdaki camur lekesini nasil cikarabilirim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q10", question: "Halimdaki meyve suyu lekesini nasil cikarabilirim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q11", question: "Halimdaki ketcap lekesini nasil cikarabilirim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q12", question: "Halimdaki sos lekesini nasil cikarabilirim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q13", question: "Halimdaki ayak izi lekesini nasil cikarabilirim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q14", question: "Halimdaki evcil hayvan lekesini nasil cikarabilirim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q15", question: "Halimdaki mum lekesini nasil cikarabilirim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q16", question: "Halimdaki rimel lekesini nasil cikarabilirim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q17", question: "Halimdaki ruj lekesini nasil cikarabilirim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q18", question: "Halimdaki tukuruk lekesini nasil cikarabilirim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q19", question: "Halimdaki nane surubu lekesini nasil cikarabilirim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q20", question: "Halimdaki bal lekesini nasil cikarabilirim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q21", question: "Halimdaki recel lekesini nasil cikarabilirim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q22", question: "Halimdaki sut lekesini nasil cikarabilirim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q23", question: "Halimdaki limonata lekesini nasil cikarabilirim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q24", question: "Halimdaki cilek lekesini nasil cikarabilirim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q25", question: "Kahve lekesi haliya bulasti, nasil temizlerim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q26", question: "Cay lekesi haliya bulasti, nasil temizlerim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q27", question: "Sarap lekesi haliya bulasti, nasil temizlerim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q28", question: "Yag lekesi haliya bulasti, nasil temizlerim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q29", question: "Cikolata lekesi haliya bulasti, nasil temizlerim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q30", question: "Kan lekesi haliya bulasti, nasil temizlerim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q31", question: "Murekkep lekesi haliya bulasti, nasil temizlerim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q32", question: "Boya lekesi haliya bulasti, nasil temizlerim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q33", question: "Camur lekesi haliya bulasti, nasil temizlerim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q34", question: "Meyve suyu lekesi haliya bulasti, nasil temizlerim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q35", question: "Ketcap lekesi haliya bulasti, nasil temizlerim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q36", question: "Sos lekesi haliya bulasti, nasil temizlerim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q37", question: "Ayak izi lekesi haliya bulasti, nasil temizlerim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q38", question: "Evcil hayvan lekesi haliya bulasti, nasil temizlerim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q39", question: "Mum lekesi haliya bulasti, nasil temizlerim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q40", question: "Rimel lekesi haliya bulasti, nasil temizlerim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q41", question: "Ruj lekesi haliya bulasti, nasil temizlerim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q42", question: "Tukuruk lekesi haliya bulasti, nasil temizlerim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q43", question: "Nane surubu lekesi haliya bulasti, nasil temizlerim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q44", question: "Bal lekesi haliya bulasti, nasil temizlerim?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q45", question: "Recel lekesi haliya bulasti, nasil temizlerim?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q46", question: "Sut lekesi haliya bulasti, nasil temizlerim?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q47", question: "Limonata lekesi haliya bulasti, nasil temizlerim?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q48", question: "Cilek lekesi haliya bulasti, nasil temizlerim?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q49", question: "Halida olusan kahve lekesi icin bakim oneriniz var mi?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q50", question: "Halida olusan cay lekesi icin bakim oneriniz var mi?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q51", question: "Halida olusan sarap lekesi icin bakim oneriniz var mi?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q52", question: "Halida olusan yag lekesi icin bakim oneriniz var mi?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q53", question: "Halida olusan cikolata lekesi icin bakim oneriniz var mi?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q54", question: "Halida olusan kan lekesi icin bakim oneriniz var mi?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q55", question: "Halida olusan murekkep lekesi icin bakim oneriniz var mi?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q56", question: "Halida olusan boya lekesi icin bakim oneriniz var mi?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q57", question: "Halida olusan camur lekesi icin bakim oneriniz var mi?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q58", question: "Halida olusan meyve suyu lekesi icin bakim oneriniz var mi?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q59", question: "Halida olusan ketcap lekesi icin bakim oneriniz var mi?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q60", question: "Halida olusan sos lekesi icin bakim oneriniz var mi?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q61", question: "Halida olusan ayak izi lekesi icin bakim oneriniz var mi?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q62", question: "Halida olusan evcil hayvan lekesi icin bakim oneriniz var mi?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q63", question: "Halida olusan mum lekesi icin bakim oneriniz var mi?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q64", question: "Halida olusan rimel lekesi icin bakim oneriniz var mi?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q65", question: "Halida olusan ruj lekesi icin bakim oneriniz var mi?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q66", question: "Halida olusan tukuruk lekesi icin bakim oneriniz var mi?", customerType: "visitor", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q67", question: "Halida olusan nane surubu lekesi icin bakim oneriniz var mi?", customerType: "registered", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q68", question: "Halida olusan bal lekesi icin bakim oneriniz var mi?", customerType: "dealer", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q69", question: "Halida olusan recel lekesi icin bakim oneriniz var mi?", customerType: "corporate", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q70", question: "Halida olusan sut lekesi icin bakim oneriniz var mi?", customerType: "employee", expectedStatus: "grounded", expectedDocumentId: "doc-bakim-001" },
	{ id: "q71", question: "Garanti suresi ne kadar?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q72", question: "Urunum icin garanti sartlari nelerdir?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q73", question: "Garanti kapsami hakkinda bilgi verir misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q74", question: "Kac yil garantiniz var?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q75", question: "Garanti suresi dolmadan once ne yapmaliyim?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q76", question: "Garanti belgesi sartlarini ogrenebilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q77", question: "Urun garantisi ile ilgili detay istiyorum.", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q78", question: "Garanti suresi konusunda net bir bilgi alabilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q79", question: "Garanti kosullariniz nelerdir, aciklar misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q80", question: "Yeni aldigim urunun garanti suresi kac yil?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q81", question: "Merhaba, Garanti suresi ne kadar?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q82", question: "Merhaba, Urunum icin garanti sartlari nelerdir?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q83", question: "Merhaba, Garanti kapsami hakkinda bilgi verir misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q84", question: "Merhaba, Kac yil garantiniz var?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q85", question: "Merhaba, Garanti suresi dolmadan once ne yapmaliyim?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q86", question: "Merhaba, Garanti belgesi sartlarini ogrenebilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q87", question: "Merhaba, Urun garantisi ile ilgili detay istiyorum.", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q88", question: "Merhaba, Garanti suresi konusunda net bir bilgi alabilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q89", question: "Merhaba, Garanti kosullariniz nelerdir, aciklar misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q90", question: "Merhaba, Yeni aldigim urunun garanti suresi kac yil?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q91", question: "Selam, Garanti suresi ne kadar?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q92", question: "Selam, Urunum icin garanti sartlari nelerdir?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q93", question: "Selam, Garanti kapsami hakkinda bilgi verir misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q94", question: "Selam, Kac yil garantiniz var?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q95", question: "Selam, Garanti suresi dolmadan once ne yapmaliyim?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q96", question: "Selam, Garanti belgesi sartlarini ogrenebilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q97", question: "Selam, Urun garantisi ile ilgili detay istiyorum.", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q98", question: "Selam, Garanti suresi konusunda net bir bilgi alabilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q99", question: "Selam, Garanti kosullariniz nelerdir, aciklar misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q100", question: "Selam, Yeni aldigim urunun garanti suresi kac yil?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q101", question: "Bir sorum olacakti: Garanti suresi ne kadar?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q102", question: "Bir sorum olacakti: Urunum icin garanti sartlari nelerdir?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q103", question: "Bir sorum olacakti: Garanti kapsami hakkinda bilgi verir misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q104", question: "Bir sorum olacakti: Kac yil garantiniz var?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q105", question: "Bir sorum olacakti: Garanti suresi dolmadan once ne yapmaliyim?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q106", question: "Bir sorum olacakti: Garanti belgesi sartlarini ogrenebilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q107", question: "Bir sorum olacakti: Urun garantisi ile ilgili detay istiyorum.", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q108", question: "Bir sorum olacakti: Garanti suresi konusunda net bir bilgi alabilir miyim?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q109", question: "Bir sorum olacakti: Garanti kosullariniz nelerdir, aciklar misiniz?", customerType: "visitor", expectedStatus: "conflicting_sources" },
	{ id: "q110", question: "Bir sorum olacakti: Yeni aldigim urunun garanti suresi kac yil?", customerType: "registered", expectedStatus: "conflicting_sources" },
	{ id: "q111", question: "Bayi komisyon politikaniz nedir?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q112", question: "Bayilere ozel komisyon oranlari hakkinda bilgi verir misiniz?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q113", question: "Bayi komisyon yuzdesi ne kadar?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q114", question: "Bayi olarak komisyon kosullarimi ogrenebilir miyim?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q115", question: "Ic komisyon politikasi dokumanina ulasabilir miyim?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q116", question: "Bayi komisyon oranlarini degistirdiniz mi?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q117", question: "Komisyon politikasi hangi kaynakta anlatiliyor?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q118", question: "Bayi komisyonu nasil hesaplaniyor?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q119", question: "Bayi komisyon politikaniz nedir?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q120", question: "Bayilere ozel komisyon oranlari hakkinda bilgi verir misiniz?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q121", question: "Bayi komisyon yuzdesi ne kadar?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q122", question: "Bayi olarak komisyon kosullarimi ogrenebilir miyim?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q123", question: "Ic komisyon politikasi dokumanina ulasabilir miyim?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q124", question: "Bayi komisyon oranlarini degistirdiniz mi?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q125", question: "Komisyon politikasi hangi kaynakta anlatiliyor?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q126", question: "Bayi komisyonu nasil hesaplaniyor?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q127", question: "Bayi komisyon politikaniz nedir?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q128", question: "Bayilere ozel komisyon oranlari hakkinda bilgi verir misiniz?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q129", question: "Bayi komisyon yuzdesi ne kadar?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q130", question: "Bayi olarak komisyon kosullarimi ogrenebilir miyim?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q131", question: "Ic komisyon politikasi dokumanina ulasabilir miyim?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q132", question: "Bayi komisyon oranlarini degistirdiniz mi?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q133", question: "Komisyon politikasi hangi kaynakta anlatiliyor?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q134", question: "Bayi komisyonu nasil hesaplaniyor?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q135", question: "Bayi komisyon politikaniz nedir?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q136", question: "Bayilere ozel komisyon oranlari hakkinda bilgi verir misiniz?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q137", question: "Bayi komisyon yuzdesi ne kadar?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q138", question: "Bayi olarak komisyon kosullarimi ogrenebilir miyim?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q139", question: "Ic komisyon politikasi dokumanina ulasabilir miyim?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q140", question: "Bayi komisyon oranlarini degistirdiniz mi?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q141", question: "Komisyon politikasi hangi kaynakta anlatiliyor?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q142", question: "Bayi komisyonu nasil hesaplaniyor?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q143", question: "Bayi komisyon politikaniz nedir?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q144", question: "Bayilere ozel komisyon oranlari hakkinda bilgi verir misiniz?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q145", question: "Bayi komisyon yuzdesi ne kadar?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q146", question: "Bayi olarak komisyon kosullarimi ogrenebilir miyim?", customerType: "visitor", expectedStatus: "permission_denied" },
	{ id: "q147", question: "Ic komisyon politikasi dokumanina ulasabilir miyim?", customerType: "registered", expectedStatus: "permission_denied" },
	{ id: "q148", question: "Bayi komisyon oranlarini degistirdiniz mi?", customerType: "dealer", expectedStatus: "permission_denied" },
	{ id: "q149", question: "Komisyon politikasi hangi kaynakta anlatiliyor?", customerType: "corporate", expectedStatus: "permission_denied" },
	{ id: "q150", question: "Bayi komisyonu nasil hesaplaniyor?", customerType: "employee", expectedStatus: "permission_denied" },
	{ id: "q151", question: "Kargo takip numarami nereden bulabilirim?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q152", question: "Odemem neden onaylanmadi?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q153", question: "Siparisimi iptal etmek istiyorum, nasil yapabilirim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q154", question: "Stokta hangi renkler mevcut?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q155", question: "Montaj hizmeti ucretli mi?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q156", question: "Magazanizin calisma saatleri nedir?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q157", question: "Sifremi unuttum, hesabima nasil girebilirim?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q158", question: "Kampanya kodum neden calismiyor?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q159", question: "Faturamda bir hata var, nasil duzeltebilirim?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q160", question: "Is basvurumun durumunu ogrenebilir miyim?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q161", question: "Yastigimin dikisi acildi, degistirebilir misiniz?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q162", question: "Urunun mevcut renk secenekleri nelerdir?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q163", question: "Mobilya odaya sigacak mi, nasil kontrol ederim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q164", question: "Randevu talebi icin formu nereden doldurabilirim?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q165", question: "Faturami e-posta adresime gonderebilir misiniz?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q166", question: "Musteri hizmetleri telefon numaraniz nedir?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q167", question: "Web sitenizde odeme sayfasi acilmiyor.", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q168", question: "Uyelik hesabimi nasil kapatabilirim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q169", question: "Kisisel verilerimin silinmesini talep ediyorum.", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q170", question: "Toptan siparis vermek icin kiminle gorusmeliyim?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q171", question: "Yeni koleksiyon ne zaman piyasaya sunulacak?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q172", question: "Urun kutusu hasarli geldi, ne yapmaliyim?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q173", question: "Siparis numaramla durumu sorgulayabilir miyim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q174", question: "Kredi karti taksit secenekleri nelerdir?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q175", question: "Magaza icinde otopark var mi?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q176", question: "Ambalaj geri donusumlu mu?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q177", question: "Reklamlarla ilgili bir sikayetim var, kime iletebilirim?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q178", question: "Sosyal medya hesaplariniz hangileri?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q179", question: "Bulten aboneligimi iptal etmek istiyorum.", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q180", question: "Yurtdisina teslimat yapiyor musunuz?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q181", question: "Urun numunesi gonderebilir misiniz?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q182", question: "Odeme planimi degistirebilir miyim?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q183", question: "Kurumsal fatura kesebiliyor musunuz?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q184", question: "Hediye paketi secenegi var mi?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q185", question: "Mobilyanin montaj videosu var mi?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q186", question: "Urun agirligi ne kadar?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q187", question: "Kargo firmasini degistirebilir miyim?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q188", question: "Siparisimi baska adrese yonlendirebilir miyim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q189", question: "Odeme sirasinda hata kodu aldim, ne yapmaliyim?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q190", question: "Yeni sube aciliyor mu?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q191", question: "Calisan performans degerlendirmesi nasil yapiliyor?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q192", question: "Kurye firmaniz hangisi?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q193", question: "Yeni tedarikci basvurusu icin iletisim bilgisi paylasabilir misiniz?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q194", question: "Sosyal sorumluluk projeleriniz var mi?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q195", question: "Urun katalogunu pdf formatinda gonderebilir misiniz?", customerType: "visitor", expectedStatus: "not_found" },
	{ id: "q196", question: "Showroom ziyareti icin gun/saat ayarlayabilir miyiz?", customerType: "registered", expectedStatus: "not_found" },
	{ id: "q197", question: "Whatsapp destek hattiniz var mi?", customerType: "dealer", expectedStatus: "not_found" },
	{ id: "q198", question: "Instagram uzerinden siparis verebilir miyim?", customerType: "corporate", expectedStatus: "not_found" },
	{ id: "q199", question: "Fatura adresimi guncelleyebilir miyim?", customerType: "employee", expectedStatus: "not_found" },
	{ id: "q200", question: "Indirim kuponu aktif etmek istiyorum, nasil yapabilirim?", customerType: "visitor", expectedStatus: "not_found" },
]
